Vcs
AntonGitName/AuJava2 pull request #1
Opened 2016-10-28 20:04 UTC by AntonGitName

2016-11-02 11:16 UTC, jzuken requested changes

2016-11-02 11:16 UTC, jzuken commented on lab-vcs/src/main/java/ru/mit/spbau/antonpp/vcs/core/log/CommitInfo.java
> +    @Nullable
это поле nullable, а остальные что?

2016-11-02 11:16 UTC, jzuken commented on lab-vcs/src/main/java/ru/mit/spbau/antonpp/vcs/core/log/CommitInfo.java
> + * @author Anton Mordberg
хорошо бы более адекватные комментарии всё же

2016-11-02 11:17 UTC, jzuken commented
раз мы делаем консольную утилиту, хорошо бы в конфиг добавить что-то про сборку jar-файла

2016-11-02 12:33 UTC, AntonGitName commented on lab-vcs/src/main/java/ru/mit/spbau/antonpp/vcs/core/log/CommitInfo.java
> +    @Nullable
Я использовал Nullable/NotNull для того, чтобы самому не забыть, что какие-то поля могу иметь особый смысл (например, что-то может быть null из тех соображений, что это долго считать каждый раз и поэтому их подсчёт можно закэшировать в геттере (который уже возвращает NotNull), или как тут, глобально мне всё равно какое сообщение запишется в лог, но часто есть возможность сгенерировать этот текст, поэтому я так отметил это поле, чтобы не забыть написать/вызвать метод для генерации дефолтного сообщения). По хорошему, все переменные имеет смысл проанотировать, но часто это излишне и не приносит никакой полезной информации (и когда весь код в аннотациях, то это отвлекает и не даёт сконцентрироваться на тех местах, где это действительно важно), а не редко это ещё и ведёт к бессмысленным варнингам в идее (например, у меня есть класс, который создается только через deserialize и поэтому у него пустой конструктор, и если в нем пометить поле как NotNull, то идея всегда будет ругаться на то, что конструктор это поле не инициализировал).

2016-11-02 12:36 UTC, AntonGitName commented on lab-vcs/src/main/java/ru/mit/spbau/antonpp/vcs/core/log/CommitInfo.java
> + * @author Anton Mordberg
Ох, на самом деле не хотелось писать джавадок для всего кода - я старался делать структуру прозрачно понятной, но, возможно, в некоторых местах нужно написать какие контракты соблюдаются. Добавлю джавадок к core классам.

2016-11-02 12:40 UTC, AntonGitName commented on lab-vcs/src/main/java/ru/mit/spbau/antonpp/vcs/core/Repository.java
> +                // impossible
Да, а что тут такого? getBranchHead кидает исключение только в том случае, если ветки нет, а я только что проверил что она есть, поэтому исключение не может быть никогда (можно, конечно, придумать изотерический случай с многопоточностью или refletion, но тут нет же такого). Хорошо, уберу if перенеся else блок в catch.

2016-11-02 12:44 UTC, AntonGitName commented
@jzuken 
> раз мы делаем консольную утилиту, хорошо бы в конфиг добавить что-то про сборку jar-файла

Не очень понял, о чём речь. Хочется в градле сделать таску deploy? Или про какой конфиг речь? Вообще, сейчас предполагается такая сборка: `./gradlew :lab-vcs:jar`

2016-11-02 14:27 UTC, jzuken commented on lab-vcs/src/main/java/ru/mit/spbau/antonpp/vcs/core/Repository.java
> +                // impossible
да, лучше уж так :)

2016-11-02 14:29 UTC, jzuken commented on lab-vcs/src/main/java/ru/mit/spbau/antonpp/vcs/core/log/CommitInfo.java
> +    @Nullable
я согласен почти со всем тут. просто одна аннотация среди кучи полей выглядит странновато :)

2016-11-02 14:30 UTC, jzuken commented
я понимаю, но манифест оно туда не кладёт: no main manifest attribute, in AuJava2-1.0.jar

2016-11-02 17:36 UTC, AntonGitName commented
@jzuken 
Больше похоже на то, что Вы написали `./gradlew jar` и собрали не тот модуль. Там всё в порядке с манифестом.
Короче, я добавил таску deploy и в корневой проект, и в модуль. Так что `./gradlew deploy` точно всё соберёт и напишет где jar лежит.
Добавил ещё кучу джавадоков и немножко код отшлифовал.

2016-11-03 06:07 UTC, jzuken commented
не, я всё запускал, как написано :)
ок, гляну. вы только сделайте сабмиты с новыми версиями на hwproj, чтобы я не пропускал решения

2016-11-03 20:23 UTC, jzuken requested changes

2016-11-03 20:23 UTC, jzuken commented on lab-vcs/src/test/java/ru/mit/spbau/antonpp/vcs/core/RepositoryTest.java
> +import ru.mit.spbau.antonpp.vcs.core.log.LogRecord;
а куда этот файл делся?

2016-11-04 08:07 UTC, AntonGitName commented on lab-vcs/src/test/java/ru/mit/spbau/antonpp/vcs/core/RepositoryTest.java
> +import ru.mit.spbau.antonpp.vcs.core.log.LogRecord;
Он попал в gitignore из-за того, что лежал в пакете log  ><

2016-11-05 15:25 UTC, jzuken commented
Created jar in folder `/home/me/git/au/mordberg/lab-vcs/target`
:lab-vcs:createTargetDir UP-TO-DATE
:lab-vcs:compileJava UP-TO-DATE
:lab-vcs:processResources UP-TO-DATE
:lab-vcs:classes UP-TO-DATE
:lab-vcs:jar UP-TO-DATE
:lab-vcs:deploy UP-TO-DATE
:deploy UP-TO-DATE

BUILD SUCCESSFUL

Total time: 0.939 secs
➜  me@faraway ~/git/au/mordberg git:(vcs) ✗ java -jar build/libs/AuJava2-1.0.jar                                                                               18:24:28
no main manifest attribute, in build/libs/AuJava2-1.0.jar


что я делаю не так? :)

2016-11-05 15:26 UTC, jzuken commented
а, я не оттуда jar запускал

2016-11-05 15:27 UTC, jzuken commented
log/vcs.log, я думаю, не стоит показывать в untracked, раз он служебный

2016-11-05 15:30 UTC, jzuken commented
а как переключиться на новый бранч? я сделал новый new, пишу ✗ java -jar lab-vcs-1.0.jar checkout new, оно мне говорит Could not find single commit. Found: []

2016-11-05 15:30 UTC, jzuken commented
и круто было бы где-то показывать текущий бранч. например при вызове branch без параметров

2016-11-05 15:51 UTC, AntonGitName commented
@jzuken 
> и круто было бы где-то показывать текущий бранч. например при вызове branch без параметров
status показывает текущую ветку.

> а как переключиться на новый бранч? я сделал новый new, пишу ✗ java -jar lab-vcs-1.0.jar checkout new, оно мне говорит Could not find single commit. Found: []
branch сразу делает и checkout (и не даст сделать, если есть не закоммиченные файлы). Поэтому checkout и не находил указанную ветку. Вообще, новая ветка это отдельная тема - она ещё не успела попасть в BranchResolver и единственное места, где про неё есть запись это текущий Stage. А все ветки, в которых есть коммиты, они уже в резолвере записаны.

2016-11-05 15:53 UTC, jzuken commented
ага, понял, спасибо

2016-11-05 15:54 UTC, jzuken commented
✗ java -jar lab-vcs-1.0.jar merge new                                                                 18:53:59
Failed to merge.

очень информативно. и главное, сразу понятно, что дальше делать :)

2016-11-05 15:55 UTC, jzuken commented
если что, я добавил один файл в мастер, потом сделал новый бранч, добавил другой файл туда, вернулся в мастер и попытался замерджить их

2016-11-05 15:56 UTC, jzuken commented
кусок лога (как хорошо, что он есть):

2016-11-05 18:54:06 ERROR AbstractCommand:80 - Failed to merge.
ru.mit.spbau.antonpp.vcs.core.exceptions.MergeException: Failed to commit merge
        at ru.mit.spbau.antonpp.vcs.core.revision.Stage.merge(Stage.java:310)
        at ru.mit.spbau.antonpp.vcs.core.Repository.merge(Repository.java:225)
        at ru.mit.spbau.antonpp.vcs.cli.commands.CommandMerge.runInternal(CommandMerge.java:41)
        at ru.mit.spbau.antonpp.vcs.cli.commands.AbstractCommand.run(AbstractCommand.java:37)
        at ru.mit.spbau.antonpp.vcs.Application.run(Application.java:92)
        at ru.mit.spbau.antonpp.vcs.Application.<init>(Application.java:62)
        at ru.mit.spbau.antonpp.vcs.Application.main(Application.java:67)
Caused by: ru.mit.spbau.antonpp.vcs.core.exceptions.CommitException: Failed to move file
        at ru.mit.spbau.antonpp.vcs.core.revision.Stage.commit(Stage.java:148)
        at ru.mit.spbau.antonpp.vcs.core.revision.Stage.merge(Stage.java:308)
        ... 6 more
Caused by: java.nio.file.FileAlreadyExistsException: /home/me/git/au/mordberg/lab-vcs/target/.vcs-internals/revs/f591dec073b1e471e416ee8cb979854b/files/2d94eda4319213bba047ca5fa8ce2d46
        at sun.nio.fs.UnixCopyFile.copy(UnixCopyFile.java:551)

2016-12-17 14:36 UTC, jzuken commented
положил в мастер файл, создал второй бранч, положил файл туда вторым коммитом, возвращаюсь чекаутом в мастер, а там лог оба коммита показывает, и оба файла лежат на диске. так задумано?

2016-12-18 14:29 UTC, AntonGitName commented
@jzuken

У чекаута и планировалось такое поведение (файлы, которые не в ревизии, никак не трогаются и не удаляются при чекауте) Я изменил, чтобы после чекаута сразу clean вызывался и ревизия чистенькая была. Логи тоже исправил - теперь фильтрую коммиты, которые никак не относятся к текущей ревизии.

2016-12-24 16:52 UTC, jzuken commented
ок, покатит

2016-12-24 22:45 UTC, merged