Java06. ДЗ 05, Мордберг Антон
AntonGitName/AuJava2 pull request #3
Opened 2016-12-13 05:11 UTC by AntonGitName

2016-12-24 16:37 UTC, jzuken requested changes

2016-12-24 16:37 UTC, jzuken commented on lab-torrent/torrent-client/src/main/java/ru/mit/spbau/antonpp/torrent/client/files/FileHolder.java
> +        val allBytes = Files.readAllBytes(source);
фильм таким образом не передашь, OutOfMemoryError. что с этим можно сделать?

2016-12-24 16:37 UTC, jzuken commented on lab-torrent/torrent-client/src/main/java/ru/mit/spbau/antonpp/torrent/client/exceptions/FileManagerException.java
> +public class FileManagerException extends RuntimeException {
а оно почему unchecked?

2016-12-24 16:37 UTC, jzuken commented on lab-torrent/torrent-client/src/test/java/ru/mit/spbau/antonpp/torrent/client/TorrentClientTest.java
> +    private static final Path TEST_DIR = Paths.get("./build/test");
а давайте тут Rule TemporaryFolder используем, раз уж мы их на практике проходили

2016-12-25 01:56 UTC, AntonGitName commented on lab-torrent/torrent-client/src/main/java/ru/mit/spbau/antonpp/torrent/client/files/FileHolder.java
> +        val allBytes = Files.readAllBytes(source);
Точно, исправил - теперь не храню весь файл в памяти при считывании.

2016-12-25 02:05 UTC, AntonGitName commented on lab-torrent/torrent-client/src/main/java/ru/mit/spbau/antonpp/torrent/client/exceptions/FileManagerException.java
> +public class FileManagerException extends RuntimeException {
Случайно получилось. Изначально предполагалось, что это вроде ассерта, который может сработать только, если весь клиент написан неправильно и работать тогда бессмыслено -- лучше сразу упасть, а я уже при тестировании исправлю (это слишком критичный участок кода, в котором, в принципе, не должно быть логических ошибок). Но со временем смысл ошибки изменился и теперь она может появится из-за ошибок межсетевого общения разных клиентов, и тут уже, конечно, нужно ловить ошибку, чтобы как-то отрепортиться и освободить ресурсы.

2016-12-25 02:05 UTC, AntonGitName commented on lab-torrent/torrent-client/src/test/java/ru/mit/spbau/antonpp/torrent/client/TorrentClientTest.java
> +    private static final Path TEST_DIR = Paths.get("./build/test");
Сделал

2016-12-27 20:06 UTC, jzuken commented
ок, зачтено

2016-12-28 12:22 UTC, merged